services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
      - /tmp/websockets/:/var/run/websockets

    # linux: direct to host
    # the host_app must be bound to 0.0.0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
